-- DATE TIME FUNCTIONS
-- 1. GETDATE(), getdate(), current_timestamp, sysdatetime(),
-- 2. datename(),
-- 3. datediff(),
-- 4. dateadd()

-- using date time functions
SELECT GETDATE() AS TODAY_DATE;
SELECT SYSDATETIME() AS TODAY_DATE;
SELECT CURRENT_TIMESTAMP AS TODAY_DATE;

-- datename() return the month or year of the date
-- return month
SELECT DATENAME(MONTH, CURRENT_TIMESTAMP) AS 'MONTH';

-- return year
SELECT DATENAME(YEAR, CURRENT_TIMESTAMP) AS 'YEAR';

-- RETURN WEEKDAY
SELECT DATENAME(WEEKDAY, CURRENT_TIMESTAMP) AS 'WEEKDAY';

-- RETURN WEEK
SELECT DATENAME(WEEK, CURRENT_TIMESTAMP) AS 'WEEK';

-- RETURN HOURS
SELECT DATENAME(HOUR, CURRENT_TIMESTAMP) AS 'HOUR';

-- DATEDIFF() returns the difference of two dates
SELECT DATEDIFF(YEAR, 'JUNE 27 1992', 'JUNE 27 2023') AS AGE;
SELECT DATEDIFF(YEAR, 'JUNE 27 1986', CURRENT_TIMESTAMP) AS AGE_IN_MONTHS;

--DATEADD() FUNCTION ADD MONTHS, YEARS etc in a date 
SELECT DATEADD(YEAR, 100, CURRENT_TIMESTAMP) AS '100YearsFromNow';
SELECT DATEADD(MONTH, 88, CURRENT_TIMESTAMP) AS '100MonthsFromNow';